services:
  barros-db:
    image: postgres
    ports:
      - '5439:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=docs
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - docs-vol:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=email@email.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - '5000:80'
    volumes:
      - pgadmin-alm:/var/lib/pgadmin


volumes:
  docs-vol:
  pgadmin-alm: